volumes:
  postgres_volume:


services:
  app:
    build:
      context: ./app
    image: app
    container_name: app
    environment:
      TZ: Europe/Rome
    volumes:
      - ./app:/home/node/app
    ports:
      - 5173:5173
    restart: always

  api:
    build:
      context: ./api
    image: api
    container_name: api
    environment:
      TZ: Europe/Rome
      ENVIRONMENT: development
    volumes:
      - ./api:/home/node/api
    ports:
      - 3000:3000
    restart: always

  postgres:
    image: postgres:15.1
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=demoPwd
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
